### ISSUE TITLE
Tootltips break when used under a web-component with ace attached to a shadow-dom

### ISSUE THREAD

**Issue by Ryex** [mkslanc/ace-linters#114]
I was working to use Ace under a web component and attached to a shadow dom

(see https://github.com/F0rce/lit-ace for an example component)

This actually works great. right up until I go to see a hover tooltip and realize they don't show up.

Inspecting the dom tree shows the tool-tips attached to the main document body and not updating.
![image](https://github.com/mkslanc/ace-linters/assets/508861/a5eb3160-365d-448c-a255-2acda481f78f)

Hovering too much gets a error on the console about detecting an EventEmitter memory leak
```
lspWorker.ts:214 Client Message: {jsonrpc: '2.0', id: 4, method: 'textDocument/signatureHelp', params: {…}}
lspWorker.ts:214 Client Message: {jsonrpc: '2.0', id: 5, method: 'textDocument/hover', params: {…}}
lspWorker.ts:214 Client Message: {jsonrpc: '2.0', id: 6, method: 'textDocument/hover', params: {…}}
lspWorker.ts:214 Client Message: {jsonrpc: '2.0', id: 7, method: 'textDocument/hover', params: {…}}
lspWorker.ts:214 Client Message: {jsonrpc: '2.0', id: 8, method: 'textDocument/hover', params: {…}}
lspWorker.ts:214 Client Message: {jsonrpc: '2.0', id: 9, method: 'textDocument/hover', params: {…}}
lspWorker.ts:214 Client Message: {jsonrpc: '2.0', id: 10, method: 'textDocument/hover', params: {…}}
lspWorker.ts:214 Client Message: {jsonrpc: '2.0', id: 11, method: 'textDocument/hover', params: {…}}
lspWorker.ts:214 Client Message: {jsonrpc: '2.0', id: 12, method: 'textDocument/hover', params: {…}}
ace-language-client.js:2397  MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 5-session2.ic10 listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (webpack-internal:///./node_modules/.pnpm/ace-linters@1.1.2/node_modules/ace-linters/build/ace-language-client.js:2557:15)
    at MessageController.addListener (webpack-internal:///./node_modules/.pnpm/ace-linters@1.1.2/node_modules/ace-linters/build/ace-language-client.js:2573:10)
    at MessageController.postMessage (webpack-internal:///./node_modules/.pnpm/ace-linters@1.1.2/node_modules/ace-linters/build/ace-language-client.js:19448:18)
    at MessageController.doHover (webpack-internal:///./node_modules/.pnpm/ace-linters@1.1.2/node_modules/ace-linters/build/ace-language-client.js:19405:14)
    at LanguageProvider.doHover (webpack-internal:///./node_modules/.pnpm/ace-linters@1.1.2/node_modules/ace-linters/build/ace-language-client.js:20695:33)
    at HoverTooltip.eval [as $gatherData] (webpack-internal:///./node_modules/.pnpm/ace-linters@1.1.2/node_modules/ace-linters/build/ace-language-client.js:20613:18)
    at HoverTooltip.waitForHover (webpack-internal:///./node_modules/.pnpm/ace-linters@1.1.2/node_modules/ace-linters/build/ace-language-client.js:20370:18)
ProcessEmitWarning @ ace-language-client.js:2397
_addListener @ ace-language-client.js:2570
addListener @ ace-language-client.js:2578
postMessage @ ace-language-client.js:19453
doHover @ ace-language-client.js:19410
doHover @ ace-language-client.js:20700
eval @ ace-language-client.js:20618
waitForHover @ ace-language-client.js:20375
setTimeout (async)
onMouseMove @ ace-language-client.js:20364
EventEmitter._emit.EventEmitter._dispatchEvent @ ace.js:867
MouseHandler.onMouseMove @ ace.js:4314
```

**Comment by Ryex** [comment]
NVM This seems to be an issue with a session that was not bound.
